"""Export fitted sklearn histogram-boosting models as deterministic C++ data."""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

import joblib
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from engine.opponent_model_features import MODEL_FEATURE_NAMES, MODEL_FEATURE_SET_ID


def _float(value: float) -> str:
    return f"{float(value):.17g}"


def model_source(name: str, path: Path) -> tuple[str, dict]:
    model = joblib.load(path)
    if model.n_features_in_ != len(MODEL_FEATURE_NAMES):
        raise ValueError(f"{path} has {model.n_features_in_} features; expected {len(MODEL_FEATURE_NAMES)}")
    nodes = []
    roots = []
    for predictors in model._predictors:
        if len(predictors) != 1:
            raise ValueError("only binary classifiers are supported")
        roots.append(len(nodes))
        tree = predictors[0].nodes
        offset = len(nodes)
        for node in tree:
            nodes.append((
                int(node["feature_idx"]), _float(node["num_threshold"]),
                offset + int(node["left"]), offset + int(node["right"]),
                int(node["missing_go_to_left"]), int(node["is_leaf"]), _float(node["value"]),
            ))
    prefix = name.replace("-", "_")
    lines = [f"static constexpr OpponentErrorNode {prefix}_nodes[] = {{"]
    lines.extend(
        f"    {{{feature}, {threshold}, {left}u, {right}u, {missing}, {leaf}, {value}}},"
        for feature, threshold, left, right, missing, leaf, value in nodes
    )
    lines.append("};")
    lines.append(f"static constexpr std::uint32_t {prefix}_roots[] = {{")
    lines.append("    " + ", ".join(f"{root}u" for root in roots))
    lines.append("};")
    lines.append(
        f'static constexpr OpponentErrorModel {prefix}_model{{"{name}", '
        f"{_float(np.asarray(model._baseline_prediction).reshape(-1)[0])}, "
        f"{prefix}_nodes, std::size({prefix}_nodes), {prefix}_roots, std::size({prefix}_roots)}};"
    )
    metadata = {
        "id": name,
        "source": str(path),
        "sha256": hashlib.sha256(path.read_bytes()).hexdigest(),
        "trees": len(roots),
        "nodes": len(nodes),
    }
    return "\n".join(lines), metadata


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--population", type=Path, required=True)
    parser.add_argument("--personal", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    sources = []
    metadata = []
    for name, path in (
        ("population-error-v1", args.population),
        ("personal-yashdutt7-lifetime-v1", args.personal),
    ):
        source, details = model_source(name, path)
        sources.append(source)
        metadata.append(details)

    feature_names = ",\n    ".join(f'"{name}"' for name in MODEL_FEATURE_NAMES)
    provenance = "\n".join(
        f"// {item['id']}: sha256={item['sha256']}, trees={item['trees']}, nodes={item['nodes']}"
        for item in metadata
    )
    text = f"""// Generated by tools/export_opponent_error_models.py. Do not edit by hand.
// Feature set: {MODEL_FEATURE_SET_ID}
{provenance}
#pragma once

#include "ace/opponent_error_model.hpp"

#include <array>
#include <iterator>

namespace ace {{

static constexpr std::array<const char*, OpponentErrorFeatureCount> OpponentErrorFeatureNames{{
    {feature_names}
}};

{sources[0]}

{sources[1]}

}} // namespace ace
"""
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(text, encoding="utf-8")
    print(f"wrote {args.output} with {sum(item['nodes'] for item in metadata)} nodes")


if __name__ == "__main__":
    main()
